# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_rankings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 536)
        MainWindow.setMaximumSize(QtCore.QSize(778, 536))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icono.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainScrollArea.sizePolicy().hasHeightForWidth())
        self.mainScrollArea.setSizePolicy(sizePolicy)
        self.mainScrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.mainScrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainScrollArea.setLineWidth(0)
        self.mainScrollArea.setWidgetResizable(True)
        self.mainScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainScrollArea.setObjectName("mainScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.mainGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.mainGroupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainGroupBox.sizePolicy().hasHeightForWidth())
        self.mainGroupBox.setSizePolicy(sizePolicy)
        self.mainGroupBox.setMinimumSize(QtCore.QSize(760, 500))
        self.mainGroupBox.setMaximumSize(QtCore.QSize(760, 500))
        self.mainGroupBox.setStyleSheet("")
        self.mainGroupBox.setTitle("")
        self.mainGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainGroupBox.setFlat(False)
        self.mainGroupBox.setCheckable(False)
        self.mainGroupBox.setObjectName("mainGroupBox")
        self.tbw_criterio1 = QtWidgets.QTableWidget(self.mainGroupBox)
        self.tbw_criterio1.setGeometry(QtCore.QRect(15, 40, 231, 171))
        self.tbw_criterio1.setObjectName("tbw_criterio1")
        self.tbw_criterio1.setColumnCount(2)
        self.tbw_criterio1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio1.setHorizontalHeaderItem(1, item)
        self.lbl_criterio1 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_criterio1.setGeometry(QtCore.QRect(15, 10, 211, 20))
        self.lbl_criterio1.setObjectName("lbl_criterio1")
        self.tbw_criterio2 = QtWidgets.QTableWidget(self.mainGroupBox)
        self.tbw_criterio2.setGeometry(QtCore.QRect(265, 40, 231, 171))
        self.tbw_criterio2.setObjectName("tbw_criterio2")
        self.tbw_criterio2.setColumnCount(2)
        self.tbw_criterio2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio2.setHorizontalHeaderItem(1, item)
        self.lbl_criterio2 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_criterio2.setGeometry(QtCore.QRect(265, 10, 211, 20))
        self.lbl_criterio2.setObjectName("lbl_criterio2")
        self.lbl_criterio3 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_criterio3.setGeometry(QtCore.QRect(515, 10, 211, 20))
        self.lbl_criterio3.setObjectName("lbl_criterio3")
        self.tbw_criterio3 = QtWidgets.QTableWidget(self.mainGroupBox)
        self.tbw_criterio3.setGeometry(QtCore.QRect(515, 40, 231, 171))
        self.tbw_criterio3.setObjectName("tbw_criterio3")
        self.tbw_criterio3.setColumnCount(2)
        self.tbw_criterio3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio3.setHorizontalHeaderItem(1, item)
        self.tbw_criterio4 = QtWidgets.QTableWidget(self.mainGroupBox)
        self.tbw_criterio4.setGeometry(QtCore.QRect(15, 260, 231, 171))
        self.tbw_criterio4.setObjectName("tbw_criterio4")
        self.tbw_criterio4.setColumnCount(2)
        self.tbw_criterio4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio4.setHorizontalHeaderItem(1, item)
        self.lbl_criterio4 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_criterio4.setGeometry(QtCore.QRect(15, 230, 211, 20))
        self.lbl_criterio4.setObjectName("lbl_criterio4")
        self.tbw_criterio6 = QtWidgets.QTableWidget(self.mainGroupBox)
        self.tbw_criterio6.setGeometry(QtCore.QRect(515, 260, 231, 171))
        self.tbw_criterio6.setObjectName("tbw_criterio6")
        self.tbw_criterio6.setColumnCount(2)
        self.tbw_criterio6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio6.setHorizontalHeaderItem(1, item)
        self.lbl_criterio5 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_criterio5.setGeometry(QtCore.QRect(265, 230, 211, 20))
        self.lbl_criterio5.setObjectName("lbl_criterio5")
        self.tbw_criterio5 = QtWidgets.QTableWidget(self.mainGroupBox)
        self.tbw_criterio5.setGeometry(QtCore.QRect(265, 260, 231, 171))
        self.tbw_criterio5.setObjectName("tbw_criterio5")
        self.tbw_criterio5.setColumnCount(2)
        self.tbw_criterio5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbw_criterio5.setHorizontalHeaderItem(1, item)
        self.lbl_criterio6 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_criterio6.setGeometry(QtCore.QRect(515, 230, 211, 20))
        self.lbl_criterio6.setObjectName("lbl_criterio6")
        self.pbtn_actualizar = QtWidgets.QPushButton(self.mainGroupBox)
        self.pbtn_actualizar.setGeometry(QtCore.QRect(670, 450, 75, 31))
        self.pbtn_actualizar.setObjectName("pbtn_actualizar")
        self.gridLayout.addWidget(self.mainGroupBox, 0, 0, 1, 1)
        self.mainScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.mainScrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hidalgo Trading Tool - Rankings"))
        item = self.tbw_criterio1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Simbolo"))
        item = self.tbw_criterio1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntaje"))
        self.lbl_criterio1.setText(_translate("MainWindow", "TextLabel"))
        item = self.tbw_criterio2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Simbolo"))
        item = self.tbw_criterio2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntaje"))
        self.lbl_criterio2.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_criterio3.setText(_translate("MainWindow", "TextLabel"))
        item = self.tbw_criterio3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Simbolo"))
        item = self.tbw_criterio3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntaje"))
        item = self.tbw_criterio4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Simbolo"))
        item = self.tbw_criterio4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntaje"))
        self.lbl_criterio4.setText(_translate("MainWindow", "TextLabel"))
        item = self.tbw_criterio6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Simbolo"))
        item = self.tbw_criterio6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntaje"))
        self.lbl_criterio5.setText(_translate("MainWindow", "TextLabel"))
        item = self.tbw_criterio5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Simbolo"))
        item = self.tbw_criterio5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Puntaje"))
        self.lbl_criterio6.setText(_translate("MainWindow", "TextLabel"))
        self.pbtn_actualizar.setText(_translate("MainWindow", "Actualizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

